#-----------------------------------------------------------------------------------------------------
#                        DB PROPERTIES
#-----------------------------------------------------------------------------------------------------

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gocheetah-db
    password: Welcome+123
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#-----------------------------------------------------------------------------------------------------
#                        CONFIGURATION PROPERTIES
#-----------------------------------------------------------------------------------------------------

server:
  port: 9191
  servlet:
    context-path: /gocheetah-core
